# Generated by Django 5.0.6 on 2024-07-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="is_default",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="prompt",
            name="name",
            field=models.TextField(default="test"),
        ),
    ]
